[options]
addons_path = addons, odoo/addons
admin_passwd = admin
db_host = dpg-d0a8b8s9c44c738njsq0-a
db_port = 5432
db_user = odoo_db_tdy9_user
db_password = mY5vBdnCWgti8X2E02ieaGoKP93m7iQu
log_level = info