services:
  - type: web
    name: odoo-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 odoo-bin -c odoo.conf
    envVars:
      - key: PYTHON_VERSION
        value: 3.10